modLoader = "javafml" #mandatory
loaderVersion = "[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"

[[mods]] #mandatory
modId = "infinitesource" #mandatory

version = "${file.jarVersion}" #mandatory
displayName = "Infinite Source Mod" #mandatory

#logoFile = "examplemod.png" #optional
credits = "" #optional
authors = "Neylux" #optional
description = '''
Infinite Source adds a single infinite water source block.
'''
